### ISSUE TITLE
debian

### ISSUE THREAD

**Issue by gladwig2** [Tverous/pytorch-notebook#15]
Would it make sense to add
ARG DEBIAN_FRONTEND=noninteractive
so debian does not ask about geographic location?

**Comment by Tverous** [comment]
Thanks for the suggestions. But I prefer to keep the option for the users to select their geographic location. In addition, geographic information is not necessary for the packages listed in Dockerfile at the moment. As such, I will hold my stance on this matter at present.

It's also possible that I'm mistaken, so I would appreciate it if you could share your thoughts or alternative ideas with me.
