### ISSUE TITLE
uid and gid permissions on Linux

### ISSUE THREAD

**Issue by ntropy83** [Tverous/pytorch-notebook#20]
Hi there,

thank you for the amazing docker image. 
One thing I had on Linux, upon building the image for user level access, I had to set the uid and gid to 1000 by hand in the docker build script. Respectively the number I got on the system from the output of "id -g" and "id -u", otherwise it would use 0 and crash. That way it worked tho.

Greetings,
~ent

**Comment by Tverous** [comment]
Could you provide the environmental information and the command that you executed?
Thanks
