### ISSUE TITLE
got this error

### ISSUE THREAD

**Issue by kulig1985** [Tverous/pytorch-notebook#31]
Hi i got this error:

Unexpected error while saving file: Untitled.ipynb [Errno 2] No such file or directory: '/app/.~Untitled.ipynb' -> '/app/Untitled.ipynb'

why is it? 
Thank you!

**Comment by Tverous** [comment]
Could you let me know which image you were using when you encountered this issue? 

Thanks.

**Comment by kulig1985** [comment]
I ran this command from the readme.md:

docker run --rm -it  \
           --gpus all  \
           -p 8888:8888  \
           -e JUPYTER_TOKEN=passwd \
           -v /local_vol:/docker_vol  \
           tverous/pytorch-notebook:latest

I changed the volume parameter to /home/me/project:/app

**Comment by Tverous** [comment]
I can not reproduce this error on my side.

To the best of my knowledge, it could either be that you don't have the write access to /home/me/project or have a corrupted Untitled.ipynb file

Could you try saving it to a different location, maybe? Thanks.

**Comment by kulig1985** [comment]
I run chmod 777 on this folder.. and this happens when I click on Jupyter lab create new notebook button.

**Comment by Tverous** [comment]
Could you try mapping to a different volume and share the results with me? thanks

**Comment by kulig1985** [comment]
i tried, with another volume, and the same happens.. i can see this error when i start the container:

```
[E 2024-05-23 06:05:53.165 ServerApp] Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7effcd003c70>>, <Task finished name='Task-1' coro=<initialize() done, defined at /usr/local/lib/python3.10/dist-packages/jupyter_lsp/serverextension.py:15> exception=RuntimeError("can't start new thread")>)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 750, in _run_callback
        ret = callback()
      File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 774, in _discard_future_result
        future.result()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_lsp/serverextension.py", line 24, in initialize
        await nbapp.io_loop.run_in_executor(pool, manager.initialize)
      File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 266, in run_in_executor
        return self.asyncio_loop.run_in_executor(executor, func, *args)
      File "/usr/lib/python3.10/asyncio/base_events.py", line 821, in run_in_executor
        executor.submit(func, *args), loop=self)
      File "/usr/lib/python3.10/concurrent/futures/thread.py", line 176, in submit
        self._adjust_thread_count()
      File "/usr/lib/python3.10/concurrent/futures/thread.py", line 199, in _adjust_thread_count
        t.start()
      File "/usr/lib/python3.10/threading.py", line 935, in start
        _start_new_thread(self._bootstrap, ())
    RuntimeError: can't start new thread
```
I can login into the jupyter lab, but when i try to create a new notebook with python3 kernel got this:

![image](https://github.com/Tverous/pytorch-notebook/assets/12034137/117e0fc9-f74b-45e4-bd08-9e98218f4dac)

**Comment by kulig1985** [comment]
And.. the files are visible on the host machine shared folder:

![image](https://github.com/Tverous/pytorch-notebook/assets/12034137/9657adbf-82a5-4686-b627-db57e44bf825)

**Comment by Tverous** [comment]
Sorry I was out of bandwidth lately. Have you resolved the issue? If not, could you try using a different image, such as Alpine, to test the mount option on your machine again?

**Comment by Tverous** [comment]
Closing the issue if no further questions
